### PR TITLE
Update AbstractIntent.ts

### PR DESCRIPTION
**Pull request by osbob53**
Constructor Simplification: Directly initialise class properties without redundant object spread (...opt), since options is already being assigned directly.
Nonce Initialisation: Extracted nonce initialisation into a private method initializeNonce to simplify the constructor and encapsulate the logic.
Method Ordering: Grouped public and abstract methods logically, with private methods placed accordingly for better readability.
TypeScript Usage: Added protected modifier to class properties to indicate they're intended for use within this class and its subclasses, without exposing them as public API.
Async Method: Explicitly marked getSendMessageRequestProto as async to align with its content, making the asynchronous nature of the method clear.

### CODE REVIEW

**Comment by zfedoran** [comment]
Hi @tsleesg, thank you for making a contribution! 

So a couple issues, the entire package that you've been working inside of has been slowly getting pulled apart into smaller parts. The files you've made changes to are now inside of `@code-wallet/intents`. 

The `@code-wallet/library` package will be deprecated

The files in this pr can be found here:
https://github.com/code-payments/code-sdk/tree/main/packages/intents/src/intents

**Comment by tsleesg** [comment]
Thanks @zfedoran if the team eventually has time to build a backlog of issues, community can contribute!

**Comment by zfedoran** [comment]
Excellent point! I'm happy to get that started. What would help is if you have anything particular in mind. I am absolutely thrilled to have PRs come in and would love to get you credited in the release notes once the PRs are merged.

At a high level, our dev strategy boils down to "make it work", "make it better", and finally, "make it great". As you've noticed, we're currently in the "make it work" stage and just starting to get to "make it better".

Inside the "make it better" track, the first step was breaking apart multi-purpose `library` package. 

If you're looking for something larger, the library package was coincidentally the foundation behind the Code python, php, and golang SDK's. We will need to make similar changes to the other SDK's. Additionally, one of the largest missing parts in those are the `client` and `proxy` packages that exist here. Those two are critically missing on the python, php, and golang side at this point. Meaning those SDK's rely on a legacy HTTP api that will be deprecated.

**Comment by tsleesg** [comment]
@zfedoran as I get more familiarity with your many repos, please just point out the ones you think need the most attention.

Would you mind also sharing some contrib notes when you have time? Working branch etc. Don't want to create more work or break anything with your deployment pipelines. 

I have plenty of feature ideas to contribute but it looks like the core could use some love first.

**Comment by tsleesg** [comment]
@zfedoran  please check out 83b59349d46875bde6b739e9bb071c0c4e9fd372

**Pull request closed without merging**
